name: deploy-to-github-pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '05 * * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: hugo-setup
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.9'
          extended: true

      - name: submodules
        run: |
          git submodule sync && git submodule update --init

      - name: build
        run: hugo -d public --gc --minify --cleanDestinationDir

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

# EOF
